<a href="https://colab.research.google.com/github/Hyorim-Kim/numpi/blob/main/numpy3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
# 배열의 행 또는 열  추가, 삭제
import numpy as np

aa = np.eye(3)  # 3, 3 단위행렬 생성
print(aa)

bb = np.c_[aa, aa[2]]  # 2번째 열 추가
print(bb)

cc = np.r_[aa, [aa[2]]]  # 2번째 행 추가
print(cc)

print('열 삽입을 이용해 행을 열로 변환 가능')
a = np.array([1,2,3])  # 1행 3열을
print(np.c_[a])  # 3행 1열로
print(a.reshape((3, 1)))  # 위와 같음

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 1.]]
열 삽입을 이용해 행을 열로 변환 가능
[[1]
 [2]
 [3]]
[[1]
 [2]
 [3]]


In [14]:
print(a)
b = np.append(a, [4,5])  # append : 요소 추가
print(b)
c = np.insert(a, 0, [6,7])  # insert : 삽입
print(c)
d = np.delete(a, 1)
print(d)

[1 2 3]
[1 2 3 4 5]
[6 7 1 2 3]
[1 3]


In [22]:
aa = np.arange(1, 10).reshape(3, 3)
print(aa)
print(np.insert(aa, 1, 99))  # 2차원 -> 1차원 차원축소
print()
print(np.insert(aa, 1, 99, axis=0))  # 행 기준, axis가 존재할 때는 차원을 유지한다.
print(np.insert(aa, 1, 99, axis=1))  # 열 기준

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[ 1 99  2  3  4  5  6  7  8  9]

[[ 1  2  3]
 [99 99 99]
 [ 4  5  6]
 [ 7  8  9]]
[[ 1 99  2  3]
 [ 4 99  5  6]
 [ 7 99  8  9]]


In [27]:
bb = np.arange(10, 19).reshape(3, 3)
print(bb)
cc = np.append(aa, bb)  # 배열 값 추가
print(cc)  # axis가 없어 차원축소

print()
cc = np.append(aa, bb, axis=0)
print(cc)
print()
cc = np.append(aa, bb, axis=1)
print(cc)

[[10 11 12]
 [13 14 15]
 [16 17 18]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


In [30]:
print(aa)
print(np.delete(aa, 1))
print(np.delete(aa, 1, axis=0))
print(np.delete(aa, 1, axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 3 4 5 6 7 8 9]
[[1 2 3]
 [7 8 9]]
[[1 3]
 [4 6]
 [7 9]]


In [42]:
# 조건 연산 : where(조건, 참, 거짓)
x = np.array([1,2,3])
y = np.array([4,5,6])
conditionData = np.array([True, False, True])
result = np.where(conditionData, x, y)  # 참이면 x, 거짓이면 y 값을 출력
print(result)

aa = np.where(x >= 2)
print(aa, x[aa])
print(np.where(x >=2, 'T', 'F'))
print(np.where(x >=2, x, x+100))
print()
bb = np.random.randn(4,4)  # 정규분포를 따르는 4*4 행렬
print(bb)
print()
print(np.where(bb > 0, 10, bb))

[1 5 3]
(array([1, 2]),) [2 3]
['F' 'T' 'T']
[101   2   3]

[[ 0.4194546  -0.76500499 -0.38698909 -1.22100145]
 [-0.16252286 -0.80426002  0.72003634 -0.76816121]
 [-0.20972293  0.43536748  0.16019883 -1.89155603]
 [ 0.70193547 -0.55315039 -1.5732689  -0.25993695]]

[[10.         -0.76500499 -0.38698909 -1.22100145]
 [-0.16252286 -0.80426002 10.         -0.76816121]
 [-0.20972293 10.         10.         -1.89155603]
 [10.         -0.55315039 -1.5732689  -0.25993695]]


In [52]:
print(x)
print(y)
mbc = np.concatenate([x, y])  # 배열 결합
print(mbc)

x1, x2 = np.split(mbc, 2)
print(x1)
print(x2)
print()
a = np.arange(1,17).reshape(4,4)
print(a)
print()
x1, x2 = np.hsplit(a,2)
print(x1)
print(x2)
print()
x1, x2 = np.vsplit(a,2)
print(x1)
print(x2)

[1 2 3]
[4 5 6]
[1 2 3 4 5 6]
[1 2 3]
[4 5 6]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
[[ 3  4]
 [ 7  8]
 [11 12]
 [15 16]]

[[1 2 3 4]
 [5 6 7 8]]
[[ 9 10 11 12]
 [13 14 15 16]]


In [71]:
# sampline : 표본 추출
li = np.array([1,2,3,4,5,6,7])

# 복원 추출
for _ in range(5):
  print(li[np.random.randint(0, len(li)-1)], end = ' ')

print()
# 비복원 추출
import random
print(random.sample(list(li), k=5))  # 중복되지 않음

print(random.sample(range(1, 46), k=6))

print(list(np.random.choice(range(1, 46), 6)))  # 기본값 replace=False
print(list(np.random.choice(range(1, 46), 6, replace=False)))  # 비복원
print(list(np.random.choice(range(1, 46), 6, replace=True)))  # 복원(중복 허용)

# 가중치를 부여한 랜덤 추출
ar = 'air book cat desk e f god'
ar = ar.split(sep=' ')
print(ar)
print(np.random.choice(ar, 3, p=[0.1,0.1,0.1,0.1,0.1,0.1,0.4]))  # god가 나올 확률이 큼

4 4 5 2 3 
[3, 1, 7, 6, 5]
[22, 28, 41, 17, 9, 43]
[33, 2, 15, 7, 34, 11]
[40, 19, 44, 7, 3, 41]
[42, 5, 7, 5, 45, 26]
['air', 'book', 'cat', 'desk', 'e', 'f', 'god']
['god' 'god' 'god']
