<a href="https://colab.research.google.com/github/Hyorim-Kim/numpi/blob/main/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [106]:
!uname -a
!cat /etc/*release
!man

Linux 84be3b699a18 5.15.120+ #1 SMP Wed Aug 30 11:19:59 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.2 LTS"
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
This system has been minimized by removing packages and content that are
not required on a system that users do not log into.

To restore this content, including manpages, you can run the 'unminimize'
command. You will still need to ensure the 'man-db' package is installed.


In [107]:
# 수식을 통해 결과를 얻을 수 있으나 외부 모듈을 사용하면 수식 없이 빠르게 결과를 얻을 수 있다.
# 개념을 이해하고 함수나 메소드를 활용하자 !!!
# 평균, 분산, 표준 편차 구하기

grades = [1,3,-2,4]

def grades_sum(grades):
  tot = 0
  for g in grades:
    tot += g
  return tot

def grades_avg(grades):
  tot = grades_sum(grades)
  ave = tot / len(grades)
  return ave

def grades_variance(grades):
  ave = grades_avg(grades)
  vari = 0
  for su in grades:
    vari += (su - ave) ** 2
  return vari / len(grades)  # 모집단으로 계산
  #return vari / (len(grades) - 1)  # 표본집단으로 계산

def grades_std(grades):
  return grades_variance(grades) ** 0.5

In [108]:
print('합은 : ', grades_sum(grades))
print('평균은 : ', grades_avg(grades))
print('분산은 : ', grades_variance(grades))
print('표준편차는 : ', grades_std(grades))

import numpy as np
print('합은 : ', np.sum(grades))
print('평균은 : ', np.mean(grades), ' ', np.average(grades))  # 둘이 다름, mean 사용하기
print('분산은 : ', np.var(grades))
print('표준편차는 : ', np.std(grades))

합은 :  6
평균은 :  1.5
분산은 :  5.25
표준편차는 :  2.29128784747792
합은 :  6
평균은 :  1.5   1.5
분산은 :  5.25
표준편차는 :  2.29128784747792


In [109]:
# numpy 모듈(라이브러리)
# 다차원 배열 자료구조인 ndarray, 선형대수 계산, 벡터 연산, 미적분 등을 지원
import numpy as np
ss = ['tom', 'oscar', 'john', 12, 12.3]  # 다양한 type의 요소
print(ss, type(ss))  # <class 'list'>
ss2 = np.array(ss)
print(ss2, type(ss2))  # <class 'numpy.ndarray'>로 변환, 같은 type으로 요소값 구성. 상위 type으로 변환 int -> float -> complex -> str

['tom', 'oscar', 'john', 12, 12.3] <class 'list'>
['tom' 'oscar' 'john' '12' '12.3'] <class 'numpy.ndarray'>


In [110]:
# 메모리 비교(list vs ndarray)
# list
li = list(range(1, 10))
print(li)
print(id(li[0]), id(li[1]))
print(li * 10)
for i in li:
  print(i * 10, end=' ')

print('\n')
# ndarray
num_arr = np.array(li)
print(num_arr)
print(id(num_arr[0]), id(num_arr[0]))
print(num_arr * 10)

[1, 2, 3, 4, 5, 6, 7, 8, 9]
139837604839664 139837604839696
[1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9]
10 20 30 40 50 60 70 80 90 

[1 2 3 4 5 6 7 8 9]
139836329138224 139836329138224
[10 20 30 40 50 60 70 80 90]


In [111]:
a = np.array([1.,2,3])  # 1차원 배열
print(a, type(a), a.dtype, a.shape, a.size)
print(a[0], a[2])
a[0] = 7
print(a)

[1. 2. 3.] <class 'numpy.ndarray'> float64 (3,) 3
1.0 3.0
[7. 2. 3.]


In [112]:
b = np.array([[1,2,3], [4,5,6]], dtype='float32')  # 2차원 배열
print(b, type(b), b.dtype, b.shape, b.size)
print(b[0,0], b[0,2])  # 1 3 (scala가 return 됨)
print(b[[0]])  # [[1 2 3]] (차원을 유지함)

[[1. 2. 3.]
 [4. 5. 6.]] <class 'numpy.ndarray'> float32 (2, 3) 6
1.0 3.0
[[1. 2. 3.]]


In [113]:
c = np.zeros((2, 2))  # 0으로 채우기
print(c)

d = np.ones((2, 2))  # 1로 채우기
print(d)

e = np.full((2, 2), 7)  # 특정 숫자로 채우기
print(e)

f = np.eye(3)  # 3행3렬, 정방행렬 만들어짐
print(f)  # 주대각만 1이고 나머지가 0

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]
[[7 7]
 [7 7]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [114]:
np.random.seed(0)  # 난수 고정
print(np.random.rand(5))  # 균등분포를 따르는 난수(사각형 모양)
print(np.random.randn(5))  # 정규분포를 따르는 난수(종모양의 좌우대칭)

print(np.random.randint(10, size=6))  # 0이상 10미만의 수 6개
print(np.random.randint(10, size=(3, 4)))  # 3행 4열, 2차원 평면
print(np.random.randint(10, size=(3, 4, 5)))  # 3면 4행 5열, 3차원

[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
[-0.84272405  1.96992445  1.26611853 -0.50587654  2.54520078]
[5 9 8 9 4 3]
[[0 3 5 0]
 [2 3 8 1]
 [3 3 3 7]]
[[[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]

 [[4 3 4 4 8]
  [4 3 7 5 5]
  [0 1 5 9 3]
  [0 5 0 1 2]]]


In [121]:
# 인덱싱, 슬라이싱
a = np.array([1,2,3,4,5])
print(a)
print(a[0])
print(a[1:3])
print(a[1:5:2])

print()
b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(b)
print(b[:])
print(b[0,0])
print(b[[0]])
print(b[[0]], b[0], b[0][0])  # [[1 2 3 4]] [1 2 3 4] 1, 마지막은 0의 0번째 요소이기 때문에 scala 형태
print(b[1:, 0:2])  # 1행부터, 0열1열 슬라이싱

print()
c = b[:2, 1:3]  # sub array, 원본은 b가 갖고있음
print(c)
print(c[0,0])
c[0,0] = 99
print(c)
print(b)  # sub array의 값을 바꾸면 원본 값도 바뀜

[1 2 3 4 5]
1
[2 3]
[2 4]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1
[[1 2 3 4]]
[[1 2 3 4]] [1 2 3 4] 1
[[ 5  6]
 [ 9 10]]

[[2 3]
 [6 7]]
2
[[99  3]
 [ 6  7]]
[[ 1 99  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
