<a href="https://colab.research.google.com/github/Hyorim-Kim/numpi/blob/main/numpy4ex.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np

# 정규분포를 따르는 난수로 5행 4열의 배열 생성
arr = np.random.randn(5, 4)
print(arr)
print()

# 각 행에 대해 합계와 최댓값 계산 및 출력
# print(np.sum(data, axis=1))
for i in range(arr.shape[0]):
    row_sum = np.sum(arr[i, :])
    row_max = np.max(arr[i, :])

    print(f"{i+1}행 합계   : {row_sum}")
    print(f"{i+1}행 최댓값 : {row_max}")
    print()

[[ 0.73760032 -0.34631431  0.15241539  1.736788  ]
 [ 0.08156893  0.56259044 -1.36281455  0.71346742]
 [-0.68101884  0.42047372  0.57195546  1.7515537 ]
 [-2.1366645  -0.8166155   1.71909322 -1.69741697]
 [ 2.24790533 -1.54934474 -0.25127075 -1.03299169]]

1행 합계   : 2.2804893969369324
1행 최댓값 : 1.736787995210062

2행 합계   : -0.005187763451676708
2행 최댓값 : 0.7134674187735663

3행 합계   : 2.062964028611286
3행 최댓값 : 1.7515536950048385

4행 합계   : -2.9316037468142033
4행 최댓값 : 1.7190932196151902

5행 합계   : -0.5857018443399359
5행 최댓값 : 2.2479053309861694



In [21]:
import numpy as np

# 6행 6열의 다차원 zero 행렬 객체 생성
arr = np.zeros((6, 6))

# 조건1: 36개의 셀에 1~36까지 정수 채우기
arr1 = np.arange(1, 37)
arr1 = arr1.reshape(6, 6)
arr = arr + arr1

# 조건2: 2번째 행 전체 원소 출력
row_2 = arr[1, :]
print("출력 결과:", row_2)

# 조건3: 5번째 열 전체 원소 출력
col_5 = arr[:, 4]
print("출력 결과:", col_5)

# 조건4: 15~29 까지 출력
sub_arr = arr[2:5, 2:5]
print("출력 결과:\n", sub_arr)


출력 결과: [ 7.  8.  9. 10. 11. 12.]
출력 결과: [ 5. 11. 17. 23. 29. 35.]
출력 결과:
 [[15. 16. 17.]
 [21. 22. 23.]
 [27. 28. 29.]]


In [27]:
import numpy as np

# 조건1: 20~100 사이의 난수 정수를 6개 발생시켜 각 행의 시작열에 난수 정수를 저장하고, 두 번째 열부터는 1씩 증가시켜 원소 저장하기
arr = np.zeros((6, 4), dtype=float)
start_col_values = np.random.randint(20, 101, 6)

for i in range(6):
    arr[i, 0] = start_col_values[i]
    arr[i, 1:] = np.arange(start_col_values[i] + 1, start_col_values[i] + 4, dtype=float)

# 출력 예시
print("1. zero 다차원 배열 객체\n", arr)
print("\n2. 난수 정수 발생\n", "random.randint(s, e, n)\n")
print("\n3. zero 다차원 배열에 난수 정수 초기화 결과. 두 번째 열부터는 1씩 증가시켜 원소 저장하기\n", arr)

# 조건2: 첫 번째 행에 1000, 마지막 행에 6000으로 요소값 수정하기
arr[0, :] = 1000
arr[-1, :] = 6000

# 출력 예시
print("\n4. 첫 번째 행에 1000, 마지막 행에 6000으로 수정\n", arr)


1. zero 다차원 배열 객체
 [[66. 67. 68. 69.]
 [45. 46. 47. 48.]
 [67. 68. 69. 70.]
 [89. 90. 91. 92.]
 [37. 38. 39. 40.]
 [90. 91. 92. 93.]]

2. 난수 정수 발생
 random.randint(s, e, n)


3. zero 다차원 배열에 난수 정수 초기화 결과. 두 번째 열부터는 1씩 증가시켜 원소 저장하기
 [[66. 67. 68. 69.]
 [45. 46. 47. 48.]
 [67. 68. 69. 70.]
 [89. 90. 91. 92.]
 [37. 38. 39. 40.]
 [90. 91. 92. 93.]]

4. 첫 번째 행에 1000, 마지막 행에 6000으로 수정
 [[1000. 1000. 1000. 1000.]
 [  45.   46.   47.   48.]
 [  67.   68.   69.   70.]
 [  89.   90.   91.   92.]
 [  37.   38.   39.   40.]
 [6000. 6000. 6000. 6000.]]


In [28]:
import numpy as np

# 표준정규분포를 따르는 난수로 4행 5열의 다차원 배열 생성
arr = np.random.randn(4, 5)

# 배열 출력
print("~ 4행 5열 다차원 배열 ~\n", arr)

# 출력 결과
print("\n~ 출력 결과 ~")
print("평균 :", np.mean(arr))
print("합계 :", np.sum(arr))
print("표준편차 :", np.std(arr))
print("분산 :", np.var(arr))
print("최댓값 :", np.max(arr))
print("최솟값 :", np.min(arr))
print("1사분위 수 :", np.percentile(arr, 25))
print("2사분위 수 :", np.percentile(arr, 50))
print("3사분위 수 :", np.percentile(arr, 75))
print("요소값 누적합 :\n", np.cumsum(arr))


~ 4행 5열 다차원 배열 ~
 [[-0.85611059 -0.28175637  1.17089901 -2.38504437  0.27650748]
 [ 1.14109888 -2.25580628 -0.62156288  1.97886396 -1.16340016]
 [-1.2370152  -1.38795895  1.35280621 -0.66180736 -1.29268404]
 [-0.30235666 -0.40664492  1.93854081  0.46378392 -0.0583247 ]]

~ 출력 결과 ~
평균 : -0.22939860955828503
합계 : -4.587972191165701
표준편차 : 1.2363495919307204
분산 : 1.528560313467259
최댓값 : 1.9788639578881035
최솟값 : -2.3850443665380494
1사분위 수 : -1.1818039230327544
2사분위 수 : -0.35450079385762245
3사분위 수 : 0.6331126572214907
요소값 누적합 :
 [-0.85611059 -1.13786695  0.03303206 -2.3520123  -2.07550482 -0.93440594
 -3.19021222 -3.8117751  -1.83291114 -2.9963113  -4.2333265  -5.62128545
 -4.26847924 -4.9302866  -6.22297063 -6.5253273  -6.93197222 -4.99343141
 -4.5296475  -4.58797219]
