<a href="https://colab.research.google.com/github/Hyorim-Kim/numpi/blob/main/numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
# 배열 연산
import numpy as np

x = np.array([[1,2], [3,4]], dtype=np.float64)  # 명시적 형변환
y = np.arange(5,9).reshape((2,2))
y = y.astype(np.float32)
print(x, x.dtype)
print(y, y.dtype)

print(x + y)  # -, *, /
print(np.add(x, y))  # subtract, multiply, divide

[[1. 2.]
 [3. 4.]] float64
[[5. 6.]
 [7. 8.]] float32
[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [11]:
# 참고 : 연산 속도
big_arr = np.random.rand(1000000)
print(big_arr)
%timeit sum(big_arr)  # python 함수

[0.09458323 0.42581171 0.81444422 ... 0.9522743  0.17212424 0.69856833]
116 ms ± 37 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [13]:
%timeit np.sum(big_arr)  # numpy 함수(빠름)

385 µs ± 7.66 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [30]:
# 벡터 연산 (내적)  **
v = np.array([9,10])
w = np.array([11,12])
print(v * w)  # 일반 곱(외적)
print(v.dot(w))  # 내적 *
print(np.dot(v, w))  # 내적 *
print(x.dot(v))  # 1*9 + 2*10    3*9 + 4*10
print(x.dot(y))

[ 99 120]
219
219
[29. 67.]
[[19. 22.]
 [43. 50.]]


In [24]:
# numpy는 연산을 위한 함수 제공
print(np.sum(x))  # 1 2 3 4 모든 요소 합
print(np.sum(x, axis=0))  # 열에 대한 합
print(np.sum(x, axis=1))  # 행에 대한 합
print(np.mean(x))  # 평균
print(np.argmax(x))  # 최댓값의 인덱스
print(np.sqrt(x))  # 제곱근
print(np.cumsum(x))  # 누적값

10.0
[4. 6.]
[3. 7.]
2.5
3
[[1.         1.41421356]
 [1.73205081 2.        ]]
[ 1.  3.  6. 10.]


In [28]:
names = np.array(['tom', 'james', 'tom', 'oscar'])
names2 = np.array(['tom', 'page', 'john'])
print(np.unique(names))  # 중복 배제
print(np.intersect1d(names, names2))  # 교집합
print(np.intersect1d(names, names2, assume_unique=True))  # 중복이 배제된 배열을 가정하고 교집합을 계산
print(np.union1d(names, names2))  # 합집합

['james' 'oscar' 'tom']
['tom']
['tom' 'tom']
['james' 'john' 'oscar' 'page' 'tom']


In [31]:
# 전치(transpose) : 행과 열의 위치를 바꿈  **
print(x)
print(x.T)

[[1. 2.]
 [3. 4.]]
[[1. 3.]
 [2. 4.]]


In [45]:
# Broadcasting : 크기가 다른 배열 간의 연산 시, 작은 배열은 큰 배열의 크기에 맞춰져 연산한다.
# https://cafe.daum.net/flowlife/SBU0/22
x = np.arange(1,10).reshape(3,3)
print(x)
print()
y = np.array([1,0,1])
print(y)
z = np.empty_like(x)  # x와 유사한 배열 생성
#print(z)

print()
for i in range(3):
  z[i] = x[i] + y
print(z)

print()
kbs = x + y  # Broadcasting 연산 처리가 됨
print(kbs)

print('\n배열 자료를 파일 i/o')
print(x)
np.savetxt('my.txt', x)

print('\n읽을 때')
my2 = np.loadtxt('my.txt')
print(my2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[1 0 1]

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]

배열 자료를 파일 i/o
[[1 2 3]
 [4 5 6]
 [7 8 9]]

읽을 때
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
